---
title: "census"
author: "Reid Haefer"
date: "10/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
```{r}
library(pacman)
p_load(tidycensus, tidyverse,leaflet)
census_api_key("680398dff0a2f4c566f10c95888da7f25e55147b")
options(tigris_use_cache = TRUE)
```
```{r}
tract<-st_read("H:/census/data", "census_tracts") %>%
  st_transform(crs=4326)
block_group<-st_read("H:/census/data", "block_groups")%>%
  st_transform(crs=4326)

### ACS variables
acs_var <- load_variables(2016, "acs5", cache = TRUE)
```

```{r}
work_transport <- c(Drive= "B08301_002",
                    Walk= "B08301_019",
                    Bike = "B08301_018",
                    `Public Transport` = "B08301_010",
                    `Work from Home` = "B08301_021",
                    Other = "B08301_020",
                    Motorcycle = "B08301_017", 
                    Taxi = "B08301_016")
                    
  nv <- get_acs(geography = "tract", year=2016, 
                variables =  work_transport, 
                state = "NV", geometry = FALSE, summary_var = "B08301_001" )
  ca <- get_acs(geography = "tract", year=2016, 
                variables = work_transport, summary_var = "B08301_001", 
                state = "CA", geometry= FALSE)
  all.ca.nv<- data.frame(bind_rows(nv, ca))
  data<-all.ca.nv  %>%
    left_join(tract, by="GEOID") %>%
    filter(!is.na(STATEFP)) %>%
    select(-geometry)
  data %>% group_by(variable) %>% 
    summarise(total=sum(estimate)) %>%
    mutate(category=case_when(variable=="B08301_002" ~ "Drive to Work",
                              variable=="B08301_001" ~ "Total Travel to Work",
                              variable=="B08301_019" ~ "Walk to Work",
                              variable=="B08301_018" ~ "Bike to Work",
                              variable=="B08301_010" ~ "Public Transportation to Work",
                              variable=="B08301_021" ~ "Worked at Home",
                              variable=="B08301_020" ~ "Other",
                              variable=="B08301_017" ~ "Motorcycle to Work",
                              variable=="B08301_016" ~ "Taxi to Work")) %>%
  filter(variable!= "B08301_001") %>%
    mutate(total1=sum(total), percent=(total/total1)* 100)
```

